name: Linux
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Install Qt
       uses: jurplel/install-qt-action@v3
       with:
         version: '6.4.1'
         host: 'linux'
         target: 'desktop'
     - uses: actions/checkout@v3
     - name: Configure
       run: cmake -S . -B Build -DDirView_BUILD_TEST=OFF -DDirView_AUTO_RUN_TEST=OFF
     - name: Build
       run: cmake --build Build